---
galaxy_info:
  author: Aurélien Maury
  description: Bootstrap for ElementaryOS, tuned for an Asus-TP-200-S install
  company: Humanity
  license: GPLv3
  min_ansible_version: 2.0
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie

dependencies: []
