---
- hosts: localhost
  become: yes
  pre_tasks:
    - assert:
        that: ansible_distribution == '"elementary os"'
    - assert:
        that: ansible_distribution_release == 'freya'

  roles:
    - common

  vars:
    kernel_pkgs:
      - file: "linux-headers-4.4.8-040408_4.4.8-040408.201604200335_all.deb"
        sum: "a8df85bc54668e402a5a0c819b07b6104ac995c939d9a35935dc4d3b3ad401e5"
      - file: "linux-headers-4.4.8-040408-generic_4.4.8-040408.201604200335_amd64.deb"
        sum: "dd7dc3f73c0ed222d0befc0437076ec559d23cca51ea7fba6b29736250789d9c"
      - file: "linux-image-4.4.8-040408-generic_4.4.8-040408.201604200335_amd64.deb"
        sum: "2f707935676a5df8653dd4fe7f71f587dfdec22a733850721df72c399d51066e"

  tasks:
    - name: get all debian packages for kernel 4.4.8
      get_url:
        url="http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.4.8-wily/{{ item.file }}"
        dest="/opt/{{ item.file }}"
        checksum="sha256:{{ item.sum }}"
      with_items: kernel_pkgs

    - name: debian packages for kernel 4.4.8 are installed
      apt:
        deb="/opt/{{ item.file }}"
      with_items: "{{ kernel_pkgs }}"

    - name: Gnome keyring library
      apt:
        name=libgnome-keyring0

    - name: gather material for Scratch 2.0 install
      get_url:
        url="{{ item.url }}"
        dest="/opt/{{ item.file }}"
        checksum="sha256:{{ item.sum }}"
      with_items:
        - url: "http://airdownload.adobe.com/air/lin/download/2.6/AdobeAIRInstaller.bin"
          file: "AdobeAIRInstaller.bin"
          sum: "2c89002bbfd13f7c119b66380e6023a1268a7b8d66d4a2c5f287bb656ed90005"
        - url: "https://scratch.mit.edu/scratchr2/static/sa/Scratch-445.2.air"
          file: "Scratch-445.2.air"
          sum: "cdb8523ac95c7166ae60368b179b169b6543197d0e862d894016485269b9f9de"

    - name: load kernel modules
      lineinfile:
        dest="/etc/modules-load.d/touchpad.conf"
        line="elan_i2c"
        create=yes
        owner=root
        group=root
        mode=0644